export const APPBAR_TITLES = {
  SEMINAR_LIST: "Quản lí hội thảo",
  SEMINAR_DETAIL: "Chi tiết hội thảo",
  SEMINAR_CREATE: "Tạo hội thảo",
  SEMINAR_UPDATE: "Chỉnh sửa hội thảo",
  SEMINAR_REPORT: "Báo cáo hội thảo",
  BOOKING_LIST: "Quản lí lịch hẹn",
  TOPIC_LIST: "Quản lí chủ đề",
  FIELD_LIST: "Quản lí lĩnh vực",
  CATEGORY_LIST: "Quản lí thể loại",
  DEPARTMENT_LIST: "Quản lí phòng ban",
  MENTOR_LIST: "Quản lí tài khoản mentor",
  STAFF_LIST: "Quản lí tài khoản nhân viên",
  MENTOR_PROFILE: "Hồ sơ diễn giả",
  STUDENT_LIST: "Quản lí tài khoản sinh viên",
  SYSTEM_CONFIG: "Cài đặt hệ thống",
};
